"""MySQL parameter knowledge base entries."""

from src.knowledge.models import KnowledgeEntry

MYSQL_KNOWLEDGE: list[KnowledgeEntry] = [
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_buffer_pool_size",
        title="Buffer Pool Sizing — Most Critical MySQL Parameter",
        category="best_practice",
        content="innodb_buffer_pool_size is the single most important MySQL performance parameter. Set to 70-80% of system RAM for dedicated MySQL servers, 50-60% for shared servers. Must be larger than total size of working set (frequently accessed data). If buffer pool hit rate < 99%, increase size. Monitoring: SHOW ENGINE INNODB STATUS — check 'Buffer pool hit rate'.",
        source="MySQL 8.0 Reference Manual — InnoDB Buffer Pool",
        confidence=0.98,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_flush_log_at_trx_commit",
        title="Transaction Durability vs Performance",
        category="tuning_guide",
        content="Values: 0=write+flush once/sec (fastest, lose 1s data), 1=write+flush every commit (safest, ~10x slower for writes), 2=write every commit, flush once/sec (balanced — only OS crash loses data). Recommendation: For OLTP with durability requirements, use 1. For analytics/bulk loading, use 0 or 2. Combined with sync_binlog for full durability: both at 1 for ACID compliance.",
        source="MySQL 8.0 Reference Manual",
        confidence=0.95,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_flush_method",
        title="I/O Flush Method Best Practice",
        category="best_practice",
        content="On Linux: always use O_DIRECT. This bypasses OS page cache for data files (InnoDB has its own buffer pool), avoiding double-buffering. Pre-8.0.20: use O_DIRECT_NO_FSYNC for further performance. For SAN/NAS: test fsync vs O_DIRECT — some storage systems benefit from fsync. Never use O_DSYNC on Linux (it's a write-only optimization that hurts reads).",
        source="MySQL 8.0 Performance Schema documentation + community benchmarks",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_io_capacity",
        title="InnoDB I/O Capacity Configuration",
        category="tuning_guide",
        content="Set innodb_io_capacity to the IOPS your storage can handle. HDD: 200-400, SATA SSD: 2000-5000, NVMe SSD: 10000-20000. This governs background page flushing and merge buffer activity. Monitor: SHOW ENGINE INNODB STATUS — if 'pending writes' is non-zero, increase io_capacity. Set innodb_io_capacity_max to 2-4x of innodb_io_capacity for emergency flushing headroom.",
        source="MySQL 8.0 Performance Tuning Guide",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_buffer_pool_instances",
        title="Buffer Pool Instances for Concurrency",
        category="best_practice",
        content="Set to CPU core count (max 64). Each instance manages 1/N of buffer pool, reducing contention on the buffer pool mutex. Minimum: each instance should have >=1GB. Example: 8-core server with 16GB buffer pool → 8 instances (2GB each). Benefit: can improve throughput 20-30% under high concurrency (>50 connections).",
        source="MySQL 8.0 InnoDB Scalability documentation",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_log_file_size",
        title="Redo Log File Sizing",
        category="tuning_guide",
        content="Larger redo logs reduce checkpoint frequency, improving write throughput. Recommendation: 1-4GB for write-heavy OLTP. The total redo log size (innodb_log_file_size * innodb_log_files_in_group) should equal ~15-25% of buffer pool size. Monitoring: SHOW ENGINE INNODB STATUS — check log sequence number vs last checkpoint age. If frequently > 30min, increase log file size.",
        source="MySQL 8.0 InnoDB Redo Log documentation",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="max_connections",
        title="Connection Limit and Memory Trade-off",
        category="risk",
        content="Each connection allocates buffers (sort_buffer_size, read_buffer_size, etc). Setting max_connections too high paired with large per-connection buffers can cause OOM. Formula: max_memory_for_connections ≈ max_connections * (sort_buffer_size + read_buffer_size + join_buffer_size + thread_stack). Recommendation: set max_connections based on expected concurrent users + 20% headroom. Use connection pooling (ProxySQL) for large deployments.",
        source="MySQL Production Deployment Guide",
        confidence=0.95,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="sort_buffer_size",
        title="Sort Buffer Size Caution",
        category="risk",
        content="sort_buffer_size is allocated PER CONNECTION that needs a sort, not per server. Setting it high (e.g. 256MB) with 100 connections can consume 25GB RAM just for sorts. Default 256KB is fine for most workloads. Only increase if SHOW GLOBAL STATUS shows Sort_merge_passes > 0 frequently. A good starting tuning value is 1-4MB, then monitor memory usage.",
        source="MySQL Server System Variables documentation",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_thread_concurrency",
        title="Thread Concurrency and Contention",
        category="tuning_guide",
        content="Controls concurrent threads inside InnoDB. 0 (default) = unlimited. For high-concurrency OLTP (200+ connections): set to 2x CPU cores to reduce context switching overhead. If CPU usage is high but throughput plateaus, lower thread_concurrency. If CPU is underutilized at peak, increase. Note: too high values cause mutex contention; too low underutilizes CPU.",
        source="MySQL 8.0 InnoDB Performance Tuning",
        confidence=0.85,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="innodb_doublewrite",
        title="Doublewrite Buffer Safety vs Performance",
        category="risk",
        content="Disabling innodb_doublewrite improves write throughput by 30-50% but risks data corruption on partial page writes (power failure mid-write). Safe to disable only on: ZFS, BTRFS (copy-on-write filesystems), or when using FusionIO/DirectPCI SSDs with atomic writes. For standard ext4/XFS on SSD: keep enabled. The performance gain is rarely worth the corruption risk.",
        source="MySQL 8.0 InnoDB Data Storage documentation",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="sync_binlog",
        title="Binary Log Sync Frequency",
        category="tuning_guide",
        content="sync_binlog=1 (flush after every write) provides full ACID with innodb_flush_log_at_trx_commit=1 but significantly reduces write throughput (up to 50% for small transactions). sync_binlog=0 (OS decides): fastest, risk losing transactions on crash. Compromise: sync_binlog=N (flush every N commits). N=100-1000 provides good throughput while limiting potential data loss.",
        source="MySQL 8.0 Replication and Binary Log documentation",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="mysql",
        parameter_name="tmp_table_size",
        title="Internal Temp Table Sizing",
        category="tuning_guide",
        content="Maximum size of in-memory internal temporary tables. If a temp table exceeds this size, MySQL converts it to on-disk (dramatically slower). Monitoring: SHOW GLOBAL STATUS like 'Created_tmp_disk_tables'. If Created_tmp_disk_tables / Created_tmp_tables > 10%, increase tmp_table_size. Recommendation: 64MB-256MB for most workloads. Must match max_heap_table_size for consistency.",
        source="MySQL 8.0 Optimization documentation",
        confidence=0.85,
    ),
]
