"""Redis parameter knowledge base entries."""

from src.knowledge.models import KnowledgeEntry

REDIS_KNOWLEDGE: list[KnowledgeEntry] = [
    KnowledgeEntry(
        system="redis",
        parameter_name="io-threads",
        title="I/O Threading Best Practice",
        category="best_practice",
        content="Set io-threads to 2-4 on multi-core machines. More than 4 threads rarely improves throughput because Redis commands are single-threaded. io-threads-do-reads should be 'yes' when io-threads > 1 to parallelize read operations as well. A typical recommendation is io-threads = min(4, cpu_cores).",
        source="Redis documentation 7.2",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="appendfsync",
        title="AOF fsync Performance Trade-offs",
        category="tuning_guide",
        content="appendfsync has three modes: 'always' (slowest, safest — ~2000 writes/sec), 'everysec' (balanced — ~50000 writes/sec, lose up to 1 second of data), 'no' (fastest — OS flushes, lose up to 30 seconds of data). For pure performance: set appendonly=no. For durability: everysec is the standard choice. 'always' should only be used when data loss is absolutely unacceptable.",
        source="Redis persistence documentation",
        confidence=0.95,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="maxmemory-policy",
        title="Eviction Policy Selection",
        category="best_practice",
        content="For cache workloads: allkeys-lru (recent access) or allkeys-lfu (access frequency). allkeys-lfu performs better with varied access patterns. For session stores: volatile-lru or volatile-ttl. Never use noeviction for cache workloads — it leads to write failures when memory is full. allkeys-random is worst: ~52% hit rate vs ~80% for LRU in typical workloads.",
        source="Redis eviction documentation + benchmarks",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="maxmemory",
        title="Memory Limit Configuration",
        category="best_practice",
        content="Always set maxmemory to prevent OOM killer. Recommended: 70-80% of system RAM for dedicated Redis, 50-60% for shared machines. Must be less than available RAM to leave room for replication buffers, AOF rewrite buffers, and OS overhead. Monitor used_memory_rss vs maxmemory — if RSS exceeds maxmemory by >20%, consider lowering maxmemory.",
        source="Redis production checklist",
        confidence=0.95,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="hz",
        title="Hz (Task Frequency) Tuning",
        category="tuning_guide",
        content="hz controls internal task execution frequency. Default 10 is balanced. Higher values (50-100): lower latency for expiry/eviction but more CPU usage. Lower values (1-5): less CPU but higher latency spikes on expiry. For latency-sensitive workloads with many expiring keys: set hz to 100-500. For pure throughput with no expiry: set hz to 1-5.",
        source="Redis internals documentation",
        confidence=0.85,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="lazyfree-lazy-eviction",
        title="Lazyfree Parameters and Latency",
        category="best_practice",
        content="The lazyfree family (lazyfree-lazy-eviction, lazyfree-lazy-expire, lazyfree-lazy-server-del) offloads delete operations to background threads. This prevents latency spikes when deleting large keys. Recommend: enable all lazyfree options (set to 'yes') for production deployments, especially with large values (>1MB) or many evictions. The memory overhead is negligible.",
        source="Redis 4.0+ lazyfree documentation",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="repl-backlog-size",
        title="Replication Backlog Sizing",
        category="tuning_guide",
        content="repl-backlog-size determines how much replication data is buffered for reconnecting replicas. If too small, replicas trigger full syncs (expensive). Recommended sizing: (write_bytes_per_second * reconnect_time_seconds). Typical: 64MB for moderate write loads, 256MB+ for heavy write loads. Monitor: replica_reconnect_count — if >0, increase backlog.",
        source="Redis replication documentation",
        confidence=0.85,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="tcp-backlog",
        title="TCP Backlog and High Connection Rates",
        category="best_practice",
        content="tcp-backlog should match the kernel's net.core.somaxconn. Increase to 4096+ for high connection rate scenarios (>1000 connections/sec). Also raise net.core.somaxconn kernel parameter. Monitoring: if you see 'connection refused' under load, increase tcp-backlog.",
        source="Redis performance documentation",
        confidence=0.85,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="save",
        title="RDB Snapshot Impact on Performance",
        category="risk",
        content="RDB save operations fork() the Redis process, doubling memory usage momentarily and pausing all operations during the fork. For pure caching workloads: disable save (save ''). For workloads with durability requirements: keep save enabled but set longer intervals to reduce fork frequency. Warning: fork() on large memory instances (>10GB) can cause significant pause times (100ms+).",
        source="Redis persistence internals",
        confidence=0.9,
    ),
    KnowledgeEntry(
        system="redis",
        parameter_name="appendonly",
        title="AOF vs RDB Performance Trade-off",
        category="tuning_guide",
        content="appendonly=no eliminates AOF write overhead entirely — best for pure in-memory caching. appendonly=yes with appendfsync=everysec adds ~10-15% write throughput reduction but minimal read impact. For mixed read/write workloads needing durability, use aof-use-rdb-preamble=yes (hybrid persistence) which combines RDB snapshots with incremental AOF.",
        source="Redis persistence documentation",
        confidence=0.9,
    ),
]
